# Goal
int32 CMD_HOME = 1
int32 CMD_MOVE = 2
int32 CMD_GRIP = 3

int32 command
Target target       # Nested object from the msg folder
bool gripper_state

---
# Result
bool success
string message

---
# Feedback
string status